export const FETCH_BREED = 'FETCH_BREED';
export const FETCH_BREED_SUCCESS = 'FETCH_BREED_SUCCESS';
export const FETCH_BREED_FAILURE = 'FETCH_BREED_FAILURE';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const SET_API_KEY = 'SET_API_KEY';

export const END_SESSION = 'END_SESSION';