export const FETCH_BREED = 'FETCH_BREED';
export const FETCH_BREED_SUCCESS = 'FETCH_BREED_SUCCESS';
export const FETCH_BREED_FAILURE = 'FETCH_BREED_FAILURE';
export const CLEAR_BREEDS = 'CLEAR_BREEDS';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const SEARCH_IMAGES = 'SEARCH_IMAGES';
export const SEARCH_IMAGES_SUCCESS = 'SEARCH_IMAGES_SUCCESS';
export const SEARCH_IMAGES_FAILURE = 'SEARCH_IMAGES_FAILURE';

export const VOTE = 'VOTE';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_FAILURE = 'VOTE_FAILURE';

export const LOGIN = 'LOGIN';

export const SET_API_KEY = 'SET_API_KEY';

export const END_SESSION = 'END_SESSION';